name: Android CI

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    name: Build KilateIDE
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle

      - name: Install Ruby
        run: |
          sudo apt update
          sudo apt install -y ruby-full

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Build KilateIDE Release
        run: ruby build.rb -g -bls

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: kilate-ide-release
          path: app/build/outputs/apk/release/*.apk